import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] =[
  {
  id: '1',
  name: 'chicken Rice',
  price: 70,
  cookTime: '30-40',
  favorite: true,
  origins: ['Indian', 'chinese'],
  stars:4.5,
  imageUrl: 'assets/food-1.jpg',
  tags: ['Fastfood', 'Lunch'],
  },
  {
  id: '2',
  name: 'Veg soup',
  price: 30,
  cookTime: '20-30',
  favorite: false,
  origins: ['Indian', 'Italy'],
  stars:3.9,
  imageUrl: 'assets/food-2.jpg',
  tags: ['slowfood', 'soup'],
  },
  {
  id: '3',
  name: 'Full Meals',
  price: 120,
  cookTime: '30-40',
  favorite: false,
  origins: ['Indian'],
  stars:4.3,
  imageUrl: 'assets/food-3.jpg',
  tags: ['Tiffin','Lunch'],
  },
  {
  id: '4',
  name: 'Idly',
  price: 40,
  cookTime: '30-40',
  favorite: false,
  origins: ['Indian'],
  stars:4.3,
  imageUrl: 'assets/food-4.jpg',
  tags: ['Tiffin'],
  },
  {
  id: '5',
  name: 'chicken briyani',
  price: 120,
  cookTime: '40-50',
  favorite: true,
  origins: ['Indian', 'Hyderbad'],
  stars:4.1,
  imageUrl: 'assets/food-5.jpg',
  tags: ['Briyani','Lunch'],
  },
  {
  id: '6',
  name: 'Mutton briyani',
  price: 150,
  cookTime: '40-50',
  favorite: false,
  origins: ['Indian','Asian'],
  stars:4.4,
  imageUrl: 'assets/food-6.jpg',
  tags: ['Briyani','Lunch'],
  },
]
export const sample_tags:Tag[] = [
  { name: 'All', count: 6 },
  { name: 'Fastfood', count: 1 },
  { name: 'Tiffin', count: 1},
  { name: 'Lunch', count: 4},
  { name: 'slowfood', count: 1 },
  { name: 'Briyani', count: 2 },
  { name: 'soup', count: 1 },

]
